=== pnhnhuktpm2211015-ops/XML/BT_GIUAKY_XML/XSD/Bans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Bans">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ban" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ban_id" type="xs:string"/>
                            <xs:element name="soGhe" type="xs:positiveInteger"/>
                            <xs:element name="trangThai_id" type="xs:integer"/>
                            <xs:element name="trangThaiBan_id" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pnhnhuktpm2211015-ops/XML/BT_GIUAKY_XML/XML_XSD/Bans.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bans
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="Bans.xsd"
>
    <Ban>
        <ban_id>B01</ban_id>
        <soGhe>4</soGhe>
        <trangThai_id>1</trangThai_id>
        <trangThaiBan_id>1</trangThaiBan_id>
    </Ban>
    <Ban>
        <ban_id>B02</ban_id>
        <soGhe>2</soGhe>
        <trangThai_id>1</trangThai_id>
        <trangThaiBan_id>2</trangThaiBan_id>
    </Ban>
    <Ban>
        <ban_id>B03</ban_id>
        <soGhe>6</soGhe>
        <trangThai_id>0</trangThai_id>
        <trangThaiBan_id>1</trangThaiBan_id>
    </Ban>
    <Ban>
        <ban_id>B04</ban_id>
        <soGhe>4</soGhe>
        <trangThai_id>1</trangThai_id>
        <trangThaiBan_id>1</trangThaiBan_id>
    </Ban>
    <Ban>
        <ban_id>B05</ban_id>
        <soGhe>8</soGhe>
        <trangThai_id>1</trangThai_id>
        <trangThaiBan_id>2</trangThaiBan_id>
    </Ban>
    <Ban>
        <ban_id>B06</ban_id>
        <soGhe>10</soGhe>
        <trangThai_id>0</trangThai_id>
        <trangThaiBan_id>1</trangThaiBan_id>
    </Ban>
    <Ban>
        <ban_id>B07</ban_id>
        <soGhe>2</soGhe>
        <trangThai_id>1</trangThai_id>
        <trangThaiBan_id>1</trangThaiBan_id>
    </Ban>
</Bans>
