=== pnhnhuktpm2211015-ops/XML/BT_GIUAKY_XML/DTD/NhanViens.dtd
<!ELEMENT NhanViens (NhanVien+)>
<!ELEMENT NhanVien (nhanVien_id, tenNhanVien, gioiTinh, diaChi, sdt, taiKhoan, matKhau, trangThaiDangNhap)>
<!ELEMENT nhanVien_id (#PCDATA)>
<!ELEMENT tenNhanVien (#PCDATA)>
<!ELEMENT gioiTinh (#PCDATA)>
<!ELEMENT diaChi (#PCDATA)>
<!ELEMENT sdt (#PCDATA)>
<!ELEMENT taiKhoan (#PCDATA)>
<!ELEMENT matKhau (#PCDATA)>
<!ELEMENT trangThaiDangNhap (#PCDATA)>

=== pnhnhuktpm2211015-ops/XML/XML_DTD/NhanViens.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NhanViens SYSTEM "NhanViens.dtd">
<NhanViens>
    <NhanVien>
        <nhanVien_id>NV01</nhanVien_id>
        <tenNhanVien>Nguyen Van A</tenNhanVien>
        <gioiTinh>1</gioiTinh>
        <diaChi>Can Tho</diaChi>
        <sdt>0901111111</sdt>
        <taiKhoan>nva</taiKhoan>
        <matKhau>123456</matKhau>
        <trangThaiDangNhap>Active</trangThaiDangNhap>
    </NhanVien>
    <NhanVien>
        <nhanVien_id>NV02</nhanVien_id>
        <tenNhanVien>Tran Thi B</tenNhanVien>
        <gioiTinh>0</gioiTinh>
        <diaChi>HCM</diaChi>
        <sdt>0902222222</sdt>
        <taiKhoan>ttb</taiKhoan>
        <matKhau>abc123</matKhau>
        <trangThaiDangNhap>Active</trangThaiDangNhap>
    </NhanVien>
    <NhanVien>
        <nhanVien_id>NV03</nhanVien_id>
        <tenNhanVien>Le Van C</tenNhanVien>
        <gioiTinh>1</gioiTinh>
        <diaChi>Ha Noi</diaChi>
        <sdt>0903333333</sdt>
        <taiKhoan>lvc</taiKhoan>
        <matKhau>passC</matKhau>
        <trangThaiDangNhap>Inactive</trangThaiDangNhap>
    </NhanVien>
    <NhanVien>
        <nhanVien_id>NV04</nhanVien_id>
        <tenNhanVien>Pham Thi D</tenNhanVien>
        <gioiTinh>0</gioiTinh>
        <diaChi>Da Nang</diaChi>
        <sdt>0904444444</sdt>
        <taiKhoan>ptd</taiKhoan>
        <matKhau>passD</matKhau>
        <trangThaiDangNhap>Active</trangThaiDangNhap>
    </NhanVien>
    <NhanVien>
        <nhanVien_id>NV05</nhanVien_id>
        <tenNhanVien>Vo Van E</tenNhanVien>
        <gioiTinh>1</gioiTinh>
        <diaChi>Can Tho</diaChi>
        <sdt>0905555555</sdt>
        <taiKhoan>vve</taiKhoan>
        <matKhau>12345e</matKhau>
        <trangThaiDangNhap>Inactive</trangThaiDangNhap>
    </NhanVien>
    <NhanVien>
        <nhanVien_id>NV06</nhanVien_id>
        <tenNhanVien>Dang Thi F</tenNhanVien>
        <gioiTinh>0</gioiTinh>
        <diaChi>Binh Duong</diaChi>
        <sdt>0906666666</sdt>
        <taiKhoan>dtf</taiKhoan>
        <matKhau>passF</matKhau>
        <trangThaiDangNhap>Active</trangThaiDangNhap>
    </NhanVien>
    <NhanVien>
        <nhanVien_id>NV07</nhanVien_id>
        <tenNhanVien>Hoang Van G</tenNhanVien>
        <gioiTinh>1</gioiTinh>
        <diaChi>Vinh Long</diaChi>
        <sdt>0907777777</sdt>
        <taiKhoan>hvg</taiKhoan>
        <matKhau>passG</matKhau>
        <trangThaiDangNhap>Active</trangThaiDangNhap>
    </NhanVien>
</NhanViens>
