=== pnhnhuktpm2211015-ops/XML/DTD/Mons.dtd
<!ELEMENT Mons (Mon+)>
<!ELEMENT Mon (mon_id, tenMon, gia, loai_id, trangThaiMon_id)>
<!ELEMENT mon_id (#PCDATA)>
<!ELEMENT tenMon (#PCDATA)>
<!ELEMENT gia (#PCDATA)>
<!ELEMENT loai_id (#PCDATA)>
<!ELEMENT trangThaiMon_id (#PCDATA)>

=== pnhnhuktpm2211015-ops/XML/BT_GIUAKY_XML/XML_DTD/Mons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mons SYSTEM "Mons.dtd">
<Mons>
    <Mon>
        <mon_id>M01</mon_id>
        <tenMon>Cà phê sữa đá</tenMon>
        <gia>25000</gia>
        <loai_id>L01</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
    <Mon>
        <mon_id>M02</mon_id>
        <tenMon>Cà phê đen</tenMon>
        <gia>20000</gia>
        <loai_id>L01</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
    <Mon>
        <mon_id>M03</mon_id>
        <tenMon>Trà sữa trân châu</tenMon>
        <gia>30000</gia>
        <loai_id>L02</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
    <Mon>
        <mon_id>M04</mon_id>
        <tenMon>Trà sữa matcha</tenMon>
        <gia>35000</gia>
        <loai_id>L02</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
    <Mon>
        <mon_id>M05</mon_id>
        <tenMon>Sinh tố xoài</tenMon>
        <gia>40000</gia>
        <loai_id>L03</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
    <Mon>
        <mon_id>M06</mon_id>
        <tenMon>Nước ép cam</tenMon>
        <gia>35000</gia>
        <loai_id>L04</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
    <Mon>
        <mon_id>M07</mon_id>
        <tenMon>Bánh tiramisu</tenMon>
        <gia>45000</gia>
        <loai_id>L05</loai_id>
        <trangThaiMon_id>1</trangThaiMon_id>
    </Mon>
</Mons>
