=== pnhnhuktpm2211015-ops/XML/XSD/LoaiMons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="LoaiMons">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="LoaiMon" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="loai_id" type="xs:string"/>
                            <xs:element name="tenLoaiMon" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pnhnhuktpm2211015-ops/XML/XML_XSD/LoaiMons.xml
<?xml version="1.0" encoding="UTF-8"?>
<LoaiMons
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="LoaiMons.xsd"
>
    <LoaiMon>
        <loai_id>L01</loai_id>
        <tenLoaiMon>Cà phê</tenLoaiMon>
    </LoaiMon>
    <LoaiMon>
        <loai_id>L02</loai_id>
        <tenLoaiMon>Trà sữa</tenLoaiMon>
    </LoaiMon>
    <LoaiMon>
        <loai_id>L03</loai_id>
        <tenLoaiMon>Sinh tố</tenLoaiMon>
    </LoaiMon>
    <LoaiMon>
        <loai_id>L04</loai_id>
        <tenLoaiMon>Nước ép</tenLoaiMon>
    </LoaiMon>
    <LoaiMon>
        <loai_id>L05</loai_id>
        <tenLoaiMon>Bánh ngọt</tenLoaiMon>
    </LoaiMon>
    <LoaiMon>
        <loai_id>L06</loai_id>
        <tenLoaiMon>Topping</tenLoaiMon>
    </LoaiMon>
    <LoaiMon>
        <loai_id>L07</loai_id>
        <tenLoaiMon>Khác</tenLoaiMon>
    </LoaiMon>
</LoaiMons>
